apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  ports:
  - port: 9555
    targetPort: 9555
  selector:
    app: adservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: folumii/adservice:latest
        ports:
        - containerPort: 9555
        env:
        - name: MESSAGE
          value: Hello from my first microservices deployment!

#### END of ADSERVICE ###
#------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: folumii/frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of FRONTEND ###
#------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: LoadBalancer
  ports:
  - port: 7070
    targetPort: 7070
  selector:
    app: cartservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: folumii/cartservice:latest
        ports:
        - containerPort: 7070
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!    
          
 #### END of CARTSERVICE ###
#------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: checkoutservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: folumii/checkoutservice:latest
        ports:
        - containerPort: 5050
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of checkoutservice ###
#---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: currencyservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: folumii/currencyservice:latest
        ports:
        - containerPort: 7000
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of currencyservice ###
#---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 8080
  selector:
    app: emailservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: folumii/emailservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of emailservice ###
#---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: loadgenerator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: folumii/loadgenerator:latest
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of loadgenerator ###
#---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: paymentservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: folumii/paymentservice:latest
        ports:
        - containerPort: 50051
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of paymentservice ###
#---------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
---
#### END of REDISDB ###
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  ports:
  - port: 3550
    targetPort: 3550
  selector:
    app: productcatalogservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalogservice
        image: folumii/productcatalogservice:latest
        ports:
        - containerPort: 3550
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of productcatalogservice ###
#---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: recommendationservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendationservice
        image: folumii/recommendationservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of recommendationservice ###
#---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: shippingservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: folumii/shippingservice:latest
        ports:
        - containerPort: 50051
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of shippingservice ###
#---------------------------------------
